name: Pixel4XL_KSU_Build
on:
  workflow_dispatch: # 开启手动触发

jobs:
  build:
    name: Build Kernel for Pixel 4 XL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Kernel
        uses: ./
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_google_msm-4.14
          kernel-branch: lineage-21
          config: floral_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 14
          # 换成这个版本，下载成功率最高
          aosp-clang-version: r487747c 
          # 依然保持这个标志，防止汇编报错
          extra-make-args: LLVM_IAS=0
          ksu: true
          ksu-version: v0.9.5
          anykernel3: true
