name: Pixel4XL_KSU_Build
on:
  workflow_dispatch: # 开启手动触发

jobs:
  build:
    name: Build Kernel for Pixel 4 XL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Kernel
        uses: ./
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_google_msm-4.14
          kernel-branch: lineage-21
          config: floral_defconfig
          arch: arm64
          aosp-gcc: true
          # 关键：手动指定 GCC 分支，避开不存在的 android14 分支
          other-gcc64-branch: master
          other-gcc32-branch: master
          other-clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r487747c.tar.gz
          android-version: 14
          extra-make-args: LLVM_IAS=0
          ksu: true
          ksu-url: https://github.com/sukisu-ultra/sukisu-ultra
          ksu-version: main
          anykernel3: true
